name: Deploy to Poisson
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/known_hosts
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:poisson

      - name: Deploy
        run: rsync -cavz out/ delucreziis@poisson.phc.dm.unipi.it:public_html/
